[package]
name = "blockchain-simulator"
version = "0.1.0"
authors = ["Kai Mast <kaimast@cs.cornell.edu>"]
edition = "2018"

[dependencies]
log = { version="0.4" }
bincode = { version="1.2" }
futures = { version="0.3", features=["compat"] }
serde = { version="1.0", features=["derive"] }
tokio = { version="0.2", features=["tcp", "sync", "io-util", "time", "rt-threaded"], optional=true }
tokio-util = { version="0.2", features=["codec"], optional=true }
clap = { version="2.33", default-features=false, features=[ "suggestions" ], optional=true }
rand = { version="0.7" }
digest = { version="0.8" }
rsa = { version="0.2", features=["serde1"] }
bytes = { version="0.5", features=["serde"] }
sha2 = { version="0.8" }

[lib]
name = "blockchain_simulator"
path = "src/lib.rs"

[features]
server = ["clap", "tokio", "tokio-util"]
